### PR TITLE
feat: line selection highlighting

### PR DESCRIPTION
**Pull request by rich-b**
## Description

Adds selection highlight support to Line charts

## Related Issue

#374

## Screenshots (if appropriate):

image

image

image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by marshallpete** [comment]
Do you mind adding a story that demonstrates this feature?

**Comment by rich-b** [comment]
retest

**Comment by rich-b** [comment]
@marshallpete the existing story already demonstrates this.  the ChartPopover -> LineChart story has a `UNSAFE_highlightBy` control.  It can be set to `item`(default), `series`, or `dimension`.  This is the same as what we already have for the ChartPopover -> StackedBarChart story

**Comment by majornista** [comment]
I think "line highlighting" highlight the line, by drawing a stroke outline, rather than all the points in the line? Screen shot showing a Vega-Chart with a line highlighted using a stroke outline

I'm thinking of the use case where there are hundreds of points in a condensed space, so that highlighted points would overlap.

**Comment by marshallpete** [comment]
Good callout @majornista . With spectrum 2 changes we will be re-evaluating all the hover, focus and select states. I think we can revisit then.

**Review by marshallpete — APPROVED** [review]

**Pull request merged**
