### PR TITLE
Donut chart

### PR DESCRIPTION
**Pull request by JadenHowell**
## Description

This PR provides the initial legwork for supporting a donut chart following spectrum guidelines. Supports general donut use cases, as well as boolean donut charts with assumptions about the data passed in.

## Related Issue

Issue linked here: https://github.com/adobe/react-spectrum-charts/issues/28

## Motivation and Context

With a donut chart available, there are more available charts for consumers, which will allow for a wider range of data consumption. Donut charts are good for displaying segmented metrics relative to the whole.

## How Has This Been Tested?

Tests were written for all utils for the spec builder, as well as general addX sections of the donut spec builder itself. Many of these tests feel lackluster, as much of the feature for donut is on the vega processing layer rather than the javascript layer, however, there are tests for all javascript flows in my utils and spec builder. 
One place I added code without tests (besides types) is in `chartSpecBuilder.ts` where I added Donut to the build order.
I created a storybook file associated with all my stories to quickly see what was added and how to consume the api.

## Known issues

When direct labels are displayed, there can be a flicker in the chart, usually a single flicker that then is stable. Under edge cases, it can cause rapid repeated changes. This is a problem with the spec itself, as it seems to happen in the vega builder as well, so is not related to the react side of the code. I believe it has to do with the size of the circle being based on the available width / height, but direct labels writing out to the sides of the chart, which would cause the size of the donut to change.
If this bug is encountered by a consumer, they can supply a bit of extra width to the chart, which will resolve the flicker.

## Screenshots (if appropriate):
Everything Donut
Boolean Donuts

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by marshallpete** [comment]
GET_BUILD

**Comment by marshallpete** [comment]
GET_BUILD

**Comment by marshallpete** [comment]
GET_BUILD

**Comment by marshallpete** [comment]
GET_BUILD

**Review by marshallpete — DISMISSED** [review]

**Review by marshallpete — APPROVED** [review]

**Review by c-lamoureux — DISMISSED** [review]

**Review by c-lamoureux — DISMISSED** [review]

**Pull request merged**
